# initial step, build node artifacts
FROM node:lts-alpine3.15 AS node

FROM php:8.1-fpm-alpine3.15
WORKDIR /var/www/doduet

RUN addgroup ebalo
RUN echo -e "password\npassword\n" | adduser -s /bin/sh -S -u 1000 ebalo www-data
RUN addgroup ebalo ebalo

# setup node
COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/share /usr/local/share
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

# add the php extension installer and install extensions
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions
RUN install-php-extensions bz2 intl gmp mcrypt opcache pdo_mysql redis swoole xml zip @composer

# add required packets
RUN apk add git curl zip unzip

# change current user
USER ${username}:${uuid}

# copy the project folder and clone from previous step
COPY . .

# install dependencies
RUN npm install
RUN echo "{\"github-oauth\": {\"github.com\": \"$(cat .private_repo_key)\"} }" > auth.json
RUN composer install

# configure secret keys
RUN php artisan key:generate
RUN php artisan crypter:gen-key

RUN chown -R ebalo:ebalo .

EXPOSE 3000 8000
CMD php artisan serve & npm run watch
