<?php
/*
 * Copyright (c) 2022 - Do Group LLC - All Right Reserved.
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Emanuele (ebalo) Balsamo <emanuele.balsamo@do-inc.co>, 2022
 */

namespace Doinc\Modules\SmartyStreetApi\Enums;

enum CountriesISO3: string
{
    case AFG = "Afghanistan";
    case ALA = "Aland Islands";
    case ALB = "Albania";
    case DZA = "Algeria";
    case ASM = "American Samoa (USA)";
    case AND = "Andorra";
    case AGO = "Angola";
    case AIA = "Anguilla";
    case ATA = "Antarctica";
    case ATG = "Antigua Barbuda";
    case ARG = "Argentina";
    case ARM = "Armenia";
    case ABW = "Aruba";
    case AUS = "Australia";
    case AUT = "Austria";
    case AZE = "Azerbaijan";
    case BHS = "Bahamas";
    case BHR = "Bahrain";
    case BGD = "Bangladesh";
    case BRB = "Barbados";
    case BLR = "Belarus";
    case BEL = "Belgium";
    case BLZ = "Belize";
    case BEN = "Benin";
    case BMU = "Bermuda";
    case BTN = "Bhutan";
    case BOL = "Bolivia";
    case BES = "Bonaire";
    case BIH = "Bosnia Herzegovina";
    case BWA = "Botswana";
    case BRA = "Brazil";
    case IOT = "British Indian Ocean Territory";
    case VGB = "British Virgin Islands";
    case BRN = "Brunei Darussalam";
    case BGR = "Bulgaria";
    case BFA = "Burkina Faso";
    case BDI = "Burundi";
    case KHM = "Cambodia";
    case CMR = "Cameroon";
    case CAN = "Canada";
    case CPV = "Cape Verde Islands";
    case CYM = "Cayman Islands";
    case CAF = "Central African Republic";
    case TCD = "Chad";
    case CHL = "Chile";
    case CHN = "China";
    case CXR = "Christmas Island";
    case CCK = "Cocos (Keeling) Islands";
    case COL = "Colombia";
    case COM = "Comoros";
    case COD = "Democratic Republic of the Congo";
    case COG = "Congo";
    case COK = "Cook Islands";
    case CRI = "Costa Rica";
    case HRV = "Croatia";
    case CUB = "Cuba";
    case CUW = "Curacao";
    case CYP = "Cyprus";
    case CZE = "Czech Republic";
    case DNK = "Denmark";
    case DJI = "Djibouti";
    case DMA = "Dominica";
    case DOM = "Dominican Republic";
    case ECU = "Ecuador";
    case EGY = "Egypt";
    case SLV = "El Salvador";
    case GNQ = "Equatorial Guinea";
    case ERI = "Eritrea";
    case EST = "Estonia";
    case ETH = "Ethiopia";
    case FLK = "Falkland Islands";
    case FRO = "Faroe Islands";
    case FJI = "Fiji";
    case FIN = "Finland";
    case FRA = "France";
    case GUF = "French Guiana";
    case PYF = "French Polynesia";
    case ATF = "French Southern Territories";
    case GAB = "Gabon";
    case GMB = "Gambia";
    case GEO = "Georgia";
    case DEU = "Germany";
    case GHA = "Ghana";
    case GIB = "Gibraltar";
    case GRC = "Greece";
    case GRL = "Greenland";
    case GRD = "Grenada";
    case GLP = "Guadeloupe";
    case GUM = "Guam (USA)";
    case GTM = "Guatemala";
    case GGY = "Guernsey";
    case GIN = "Guinea";
    case GNB = "Guinea-Bissau";
    case GUY = "Guyana";
    case HTI = "Haiti";
    case VAT = "Holy See";
    case HND = "Honduras";
    case HKG = "Hong Kong";
    case HUN = "Hungary";
    case ISL = "Iceland";
    case IND = "India";
    case IDN = "Indonesia";
    case IRN = "Iran";
    case IRQ = "Iraq";
    case IRL = "Ireland";
    case IMN = "Isle of Man";
    case ISR = "Israel";
    case ITA = "Italy";
    case CIV = "Ivory Coast";
    case JAM = "Jamaica";
    case JPN = "Japan";
    case JEY = "Jersey";
    case JOR = "Jordan";
    case KAZ = "Kazakhstan";
    case KEN = "Kenya";
    case KIR = "Kiribati";
    case KOR = "Republic of Korea";
    case KWT = "Kuwait";
    case KGZ = "Kyrgyzstan";
    case LAO = "Laos";
    case LVA = "Latvia";
    case LBN = "Lebanon";
    case LSO = "Lesotho";
    case LBR = "Liberia";
    case LBY = "Libya";
    case LIE = "Liechtenstein";
    case LTU = "Lithuania";
    case LUX = "Luxembourg";
    case MAC = "Macao";
    case MKD = "Macedonia";
    case MDG = "Madagascar";
    case MWI = "Malawi";
    case MYS = "Malaysia";
    case MDV = "Maldives";
    case MLI = "Mali";
    case MLT = "Malta";
    case MHL = "Marshall Islands (USA)";
    case MTQ = "Martinique";
    case MRT = "Mauritania";
    case MUS = "Mauritius";
    case MYT = "Mayotte";
    case MEX = "Mexico";
    case FSM = "Micronesia (USA)";
    case MDA = "Moldova";
    case MCO = "Monaco";
    case MNG = "Mongolia";
    case MNE = "Montenegro";
    case MSR = "Montserrat";
    case MAR = "Morocco";
    case MOZ = "Mozambique";
    case MMR = "Myanmar";
    case NAM = "Namibia";
    case NRU = "Nauru";
    case NPL = "Nepal";
    case ANT = "Netherlands Antilles";
    case NLD = "Netherlands";
    case NCL = "New Caledonia";
    case NZL = "New Zealand";
    case NIC = "Nicaragua";
    case NER = "Niger";
    case NGA = "Nigeria";
    case NIU = "Niue";
    case NFK = "Norfolk Island";
    case PRK = "North Korea";
    case MNP = "Northern Mariana Islands (USA)";
    case NOR = "Norway";
    case OMN = "Oman";
    case PAK = "Pakistan";
    case PLW = "Palau (USA)";
    case PSE = "Palestinian Territory";
    case PAN = "Panama";
    case PNG = "Papua New Guinea";
    case PRY = "Paraguay";
    case PER = "Peru";
    case PHL = "Philippines";
    case PCN = "Pitcairn Island";
    case POL = "Poland";
    case PRT = "Portugal";
    case PRI = "Puerto Rico (USA)";
    case QAT = "Qatar";
    case REU = "Reunion";
    case ROU = "Romania";
    case RUS = "Russia";
    case RWA = "Rwanda";
    case BLM = "Saint Barthelemy";
    case SHN = "Saint Helena";
    case KNA = "Saint Kitts and Nevis";
    case LCA = "Saint Lucia";
    case MAF = "Saint Martin";
    case SPM = "Saint Pierre and Miquelon";
    case VCT = "Saint Vincent and the Grenadines";
    case WSM = "Samoa";
    case SMR = "San Marino";
    case STP = "Sao Tome and Principe";
    case SAU = "Saudi Arabia";
    case SEN = "Senegal";
    case SRB = "Serbia";
    case SYC = "Seychelles";
    case SLE = "Sierra Leone";
    case SGP = "Singapore";
    case SXM = "Sint Maarten (Dutch)";
    case SVK = "Slovakia";
    case SVN = "Slovenia";
    case SLB = "Solomon Islands";
    case SOM = "Somalia";
    case ZAF = "South Africa";
    case SGS = "South Georgia and the South Sandwich Islands";
    case SSD = "South Sudan";
    case ESP = "Spain";
    case LKA = "Sri Lanka";
    case SDN = "Sudan";
    case SUR = "Suriname";
    case SJM = "Svalbard and Jan Mayen Islands";
    case SWZ = "Swaziland";
    case SWE = "Sweden";
    case CHE = "Switzerland";
    case SYR = "Syria";
    case TWN = "Taiwan";
    case TJK = "Tajikistan";
    case TZA = "Tanzania";
    case THA = "Thailand";
    case TLS = "Timor-Leste";
    case TGO = "Togo";
    case TKL = "Tokelau";
    case TON = "Tonga";
    case TTO = "Trinidad and Tobago";
    case TUN = "Tunisia";
    case TUR = "Turkey";
    case TKM = "Turkmenistan";
    case TCA = "Turks and Caicos Islands";
    case TUV = "Tuvalu";
    case UGA = "Uganda";
    case UKR = "Ukraine";
    case ARE = "United Arab Emirates";
    case GBR = "United Kingdom";
    case UMI = "United States Minor Outlying Islands";
    case VIR = "US Virgin Islands";
    case USA = "United States";
    case URY = "Uruguay";
    case UZB = "Uzbekistan";
    case VUT = "Vanuatu";
    case VEN = "Venezuela";
    case VNM = "Viet Nam";
    case WLF = "Wallis and Futuna Islands";
    case ESH = "Western Sahara";
    case YEM = "Yemen";
    case ZMB = "Zambia";
    case ZWE = "Zimbabwe";
    case UNKNOWN = "";

    public static function reverse(string $name): CountriesISO3
    {
        return match ($name) {
            "AFG" => CountriesISO3::AFG,
            "ALA" => CountriesISO3::ALA,
            "ALB" => CountriesISO3::ALB,
            "DZA" => CountriesISO3::DZA,
            "ASM" => CountriesISO3::ASM,
            "AND" => CountriesISO3::AND,
            "AGO" => CountriesISO3::AGO,
            "AIA" => CountriesISO3::AIA,
            "ATA" => CountriesISO3::ATA,
            "ATG" => CountriesISO3::ATG,
            "ARG" => CountriesISO3::ARG,
            "ARM" => CountriesISO3::ARM,
            "ABW" => CountriesISO3::ABW,
            "AUS" => CountriesISO3::AUS,
            "AUT" => CountriesISO3::AUT,
            "AZE" => CountriesISO3::AZE,
            "BHS" => CountriesISO3::BHS,
            "BHR" => CountriesISO3::BHR,
            "BGD" => CountriesISO3::BGD,
            "BRB" => CountriesISO3::BRB,
            "BLR" => CountriesISO3::BLR,
            "BEL" => CountriesISO3::BEL,
            "BLZ" => CountriesISO3::BLZ,
            "BEN" => CountriesISO3::BEN,
            "BMU" => CountriesISO3::BMU,
            "BTN" => CountriesISO3::BTN,
            "BOL" => CountriesISO3::BOL,
            "BES" => CountriesISO3::BES,
            "BIH" => CountriesISO3::BIH,
            "BWA" => CountriesISO3::BWA,
            "BRA" => CountriesISO3::BRA,
            "IOT" => CountriesISO3::IOT,
            "VGB" => CountriesISO3::VGB,
            "BRN" => CountriesISO3::BRN,
            "BGR" => CountriesISO3::BGR,
            "BFA" => CountriesISO3::BFA,
            "BDI" => CountriesISO3::BDI,
            "KHM" => CountriesISO3::KHM,
            "CMR" => CountriesISO3::CMR,
            "CAN" => CountriesISO3::CAN,
            "CPV" => CountriesISO3::CPV,
            "CYM" => CountriesISO3::CYM,
            "CAF" => CountriesISO3::CAF,
            "TCD" => CountriesISO3::TCD,
            "CHL" => CountriesISO3::CHL,
            "CHN" => CountriesISO3::CHN,
            "CXR" => CountriesISO3::CXR,
            "CCK" => CountriesISO3::CCK,
            "COL" => CountriesISO3::COL,
            "COM" => CountriesISO3::COM,
            "COD" => CountriesISO3::COD,
            "COG" => CountriesISO3::COG,
            "COK" => CountriesISO3::COK,
            "CRI" => CountriesISO3::CRI,
            "HRV" => CountriesISO3::HRV,
            "CUB" => CountriesISO3::CUB,
            "CUW" => CountriesISO3::CUW,
            "CYP" => CountriesISO3::CYP,
            "CZE" => CountriesISO3::CZE,
            "DNK" => CountriesISO3::DNK,
            "DJI" => CountriesISO3::DJI,
            "DMA" => CountriesISO3::DMA,
            "DOM" => CountriesISO3::DOM,
            "ECU" => CountriesISO3::ECU,
            "EGY" => CountriesISO3::EGY,
            "SLV" => CountriesISO3::SLV,
            "GNQ" => CountriesISO3::GNQ,
            "ERI" => CountriesISO3::ERI,
            "EST" => CountriesISO3::EST,
            "ETH" => CountriesISO3::ETH,
            "FLK" => CountriesISO3::FLK,
            "FRO" => CountriesISO3::FRO,
            "FJI" => CountriesISO3::FJI,
            "FIN" => CountriesISO3::FIN,
            "FRA" => CountriesISO3::FRA,
            "GUF" => CountriesISO3::GUF,
            "PYF" => CountriesISO3::PYF,
            "ATF" => CountriesISO3::ATF,
            "GAB" => CountriesISO3::GAB,
            "GMB" => CountriesISO3::GMB,
            "GEO" => CountriesISO3::GEO,
            "DEU" => CountriesISO3::DEU,
            "GHA" => CountriesISO3::GHA,
            "GIB" => CountriesISO3::GIB,
            "GRC" => CountriesISO3::GRC,
            "GRL" => CountriesISO3::GRL,
            "GRD" => CountriesISO3::GRD,
            "GLP" => CountriesISO3::GLP,
            "GUM" => CountriesISO3::GUM,
            "GTM" => CountriesISO3::GTM,
            "GGY" => CountriesISO3::GGY,
            "GIN" => CountriesISO3::GIN,
            "GNB" => CountriesISO3::GNB,
            "GUY" => CountriesISO3::GUY,
            "HTI" => CountriesISO3::HTI,
            "VAT" => CountriesISO3::VAT,
            "HND" => CountriesISO3::HND,
            "HKG" => CountriesISO3::HKG,
            "HUN" => CountriesISO3::HUN,
            "ISL" => CountriesISO3::ISL,
            "IND" => CountriesISO3::IND,
            "IDN" => CountriesISO3::IDN,
            "IRN" => CountriesISO3::IRN,
            "IRQ" => CountriesISO3::IRQ,
            "IRL" => CountriesISO3::IRL,
            "IMN" => CountriesISO3::IMN,
            "ISR" => CountriesISO3::ISR,
            "ITA" => CountriesISO3::ITA,
            "CIV" => CountriesISO3::CIV,
            "JAM" => CountriesISO3::JAM,
            "JPN" => CountriesISO3::JPN,
            "JEY" => CountriesISO3::JEY,
            "JOR" => CountriesISO3::JOR,
            "KAZ" => CountriesISO3::KAZ,
            "KEN" => CountriesISO3::KEN,
            "KIR" => CountriesISO3::KIR,
            "KOR" => CountriesISO3::KOR,
            "KWT" => CountriesISO3::KWT,
            "KGZ" => CountriesISO3::KGZ,
            "LAO" => CountriesISO3::LAO,
            "LVA" => CountriesISO3::LVA,
            "LBN" => CountriesISO3::LBN,
            "LSO" => CountriesISO3::LSO,
            "LBR" => CountriesISO3::LBR,
            "LBY" => CountriesISO3::LBY,
            "LIE" => CountriesISO3::LIE,
            "LTU" => CountriesISO3::LTU,
            "LUX" => CountriesISO3::LUX,
            "MAC" => CountriesISO3::MAC,
            "MKD" => CountriesISO3::MKD,
            "MDG" => CountriesISO3::MDG,
            "MWI" => CountriesISO3::MWI,
            "MYS" => CountriesISO3::MYS,
            "MDV" => CountriesISO3::MDV,
            "MLI" => CountriesISO3::MLI,
            "MLT" => CountriesISO3::MLT,
            "MHL" => CountriesISO3::MHL,
            "MTQ" => CountriesISO3::MTQ,
            "MRT" => CountriesISO3::MRT,
            "MUS" => CountriesISO3::MUS,
            "MYT" => CountriesISO3::MYT,
            "MEX" => CountriesISO3::MEX,
            "FSM" => CountriesISO3::FSM,
            "MDA" => CountriesISO3::MDA,
            "MCO" => CountriesISO3::MCO,
            "MNG" => CountriesISO3::MNG,
            "MNE" => CountriesISO3::MNE,
            "MSR" => CountriesISO3::MSR,
            "MAR" => CountriesISO3::MAR,
            "MOZ" => CountriesISO3::MOZ,
            "MMR" => CountriesISO3::MMR,
            "NAM" => CountriesISO3::NAM,
            "NRU" => CountriesISO3::NRU,
            "NPL" => CountriesISO3::NPL,
            "ANT" => CountriesISO3::ANT,
            "NLD" => CountriesISO3::NLD,
            "NCL" => CountriesISO3::NCL,
            "NZL" => CountriesISO3::NZL,
            "NIC" => CountriesISO3::NIC,
            "NER" => CountriesISO3::NER,
            "NGA" => CountriesISO3::NGA,
            "NIU" => CountriesISO3::NIU,
            "NFK" => CountriesISO3::NFK,
            "PRK" => CountriesISO3::PRK,
            "MNP" => CountriesISO3::MNP,
            "NOR" => CountriesISO3::NOR,
            "OMN" => CountriesISO3::OMN,
            "PAK" => CountriesISO3::PAK,
            "PLW" => CountriesISO3::PLW,
            "PSE" => CountriesISO3::PSE,
            "PAN" => CountriesISO3::PAN,
            "PNG" => CountriesISO3::PNG,
            "PRY" => CountriesISO3::PRY,
            "PER" => CountriesISO3::PER,
            "PHL" => CountriesISO3::PHL,
            "PCN" => CountriesISO3::PCN,
            "POL" => CountriesISO3::POL,
            "PRT" => CountriesISO3::PRT,
            "PRI" => CountriesISO3::PRI,
            "QAT" => CountriesISO3::QAT,
            "REU" => CountriesISO3::REU,
            "ROU" => CountriesISO3::ROU,
            "RUS" => CountriesISO3::RUS,
            "RWA" => CountriesISO3::RWA,
            "BLM" => CountriesISO3::BLM,
            "SHN" => CountriesISO3::SHN,
            "KNA" => CountriesISO3::KNA,
            "LCA" => CountriesISO3::LCA,
            "MAF" => CountriesISO3::MAF,
            "SPM" => CountriesISO3::SPM,
            "VCT" => CountriesISO3::VCT,
            "WSM" => CountriesISO3::WSM,
            "SMR" => CountriesISO3::SMR,
            "STP" => CountriesISO3::STP,
            "SAU" => CountriesISO3::SAU,
            "SEN" => CountriesISO3::SEN,
            "SRB" => CountriesISO3::SRB,
            "SYC" => CountriesISO3::SYC,
            "SLE" => CountriesISO3::SLE,
            "SGP" => CountriesISO3::SGP,
            "SXM" => CountriesISO3::SXM,
            "SVK" => CountriesISO3::SVK,
            "SVN" => CountriesISO3::SVN,
            "SLB" => CountriesISO3::SLB,
            "SOM" => CountriesISO3::SOM,
            "ZAF" => CountriesISO3::ZAF,
            "SGS" => CountriesISO3::SGS,
            "SSD" => CountriesISO3::SSD,
            "ESP" => CountriesISO3::ESP,
            "LKA" => CountriesISO3::LKA,
            "SDN" => CountriesISO3::SDN,
            "SUR" => CountriesISO3::SUR,
            "SJM" => CountriesISO3::SJM,
            "SWZ" => CountriesISO3::SWZ,
            "SWE" => CountriesISO3::SWE,
            "CHE" => CountriesISO3::CHE,
            "SYR" => CountriesISO3::SYR,
            "TWN" => CountriesISO3::TWN,
            "TJK" => CountriesISO3::TJK,
            "TZA" => CountriesISO3::TZA,
            "THA" => CountriesISO3::THA,
            "TLS" => CountriesISO3::TLS,
            "TGO" => CountriesISO3::TGO,
            "TKL" => CountriesISO3::TKL,
            "TON" => CountriesISO3::TON,
            "TTO" => CountriesISO3::TTO,
            "TUN" => CountriesISO3::TUN,
            "TUR" => CountriesISO3::TUR,
            "TKM" => CountriesISO3::TKM,
            "TCA" => CountriesISO3::TCA,
            "TUV" => CountriesISO3::TUV,
            "UGA" => CountriesISO3::UGA,
            "UKR" => CountriesISO3::UKR,
            "ARE" => CountriesISO3::ARE,
            "GBR" => CountriesISO3::GBR,
            "UMI" => CountriesISO3::UMI,
            "VIR" => CountriesISO3::VIR,
            "USA" => CountriesISO3::USA,
            "URY" => CountriesISO3::URY,
            "UZB" => CountriesISO3::UZB,
            "VUT" => CountriesISO3::VUT,
            "VEN" => CountriesISO3::VEN,
            "VNM" => CountriesISO3::VNM,
            "WLF" => CountriesISO3::WLF,
            "ESH" => CountriesISO3::ESH,
            "YEM" => CountriesISO3::YEM,
            "ZMB" => CountriesISO3::ZMB,
            "ZWE" => CountriesISO3::ZWE,
            default => CountriesISO3::UNKNOWN
        };
    }
}
