<?php
/*
 * Copyright (c) 2022 - Do Group LLC - All Right Reserved.
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Emanuele (ebalo) Balsamo <emanuele.balsamo@do-inc.co>, 2022
 */

namespace Doinc\Modules\SmartyStreetApi\Enums;

enum CountriesISO2: string
{
    case AF = "Afghanistan";
    case AX = "Aland Islands";
    case AL = "Albania";
    case DZ = "Algeria";
    case AS = "American Samoa (USA)";
    case AD = "Andorra";
    case AO = "Angola";
    case AI = "Anguilla";
    case AQ = "Antarctica";
    case AG = "Antigua Barbuda";
    case AR = "Argentina";
    case AM = "Armenia";
    case AW = "Aruba";
    case AU = "Australia";
    case AT = "Austria";
    case AZ = "Azerbaijan";
    case BS = "Bahamas";
    case BH = "Bahrain";
    case BD = "Bangladesh";
    case BB = "Barbados";
    case BY = "Belarus";
    case BE = "Belgium";
    case BZ = "Belize";
    case BJ = "Benin";
    case BM = "Bermuda";
    case BT = "Bhutan";
    case BO = "Bolivia";
    case BQ = "Bonaire";
    case BA = "Bosnia Herzegovina";
    case BW = "Botswana";
    case BR = "Brazil";
    case IO = "British Indian Ocean Territory";
    case VG = "British Virgin Islands";
    case BN = "Brunei Darussalam";
    case BG = "Bulgaria";
    case BF = "Burkina Faso";
    case BI = "Burundi";
    case KH = "Cambodia";
    case CM = "Cameroon";
    case CA = "Canada";
    case CV = "Cape Verde Islands";
    case KY = "Cayman Islands";
    case CF = "Central African Republic";
    case TD = "Chad";
    case CL = "Chile";
    case CN = "China";
    case CX = "Christmas Island";
    case CC = "Cocos (Keeling) Islands";
    case CO = "Colombia";
    case KM = "Comoros";
    case CD = "Democratic Republic of the Congo";
    case CG = "Congo";
    case CK = "Cook Islands";
    case CR = "Costa Rica";
    case HR = "Croatia";
    case CU = "Cuba";
    case CW = "Curacao";
    case CY = "Cyprus";
    case CZ = "Czech Republic";
    case DK = "Denmark";
    case DJ = "Djibouti";
    case DM = "Dominica";
    case DO = "Dominican Republic";
    case EC = "Ecuador";
    case EG = "Egypt";
    case SV = "El Salvador";
    case GQ = "Equatorial Guinea";
    case ER = "Eritrea";
    case EE = "Estonia";
    case ET = "Ethiopia";
    case FK = "Falkland Islands";
    case FO = "Faroe Islands";
    case FJ = "Fiji";
    case FI = "Finland";
    case FR = "France";
    case GF = "French Guiana";
    case PF = "French Polynesia";
    case TF = "French Southern Territories";
    case GA = "Gabon";
    case GM = "Gambia";
    case GE = "Georgia";
    case DE = "Germany";
    case GH = "Ghana";
    case GI = "Gibraltar";
    case GR = "Greece";
    case GL = "Greenland";
    case GD = "Grenada";
    case GP = "Guadeloupe";
    case GU = "Guam (USA)";
    case GT = "Guatemala";
    case GG = "Guernsey";
    case GN = "Guinea";
    case GW = "Guinea-Bissau";
    case GY = "Guyana";
    case HT = "Haiti";
    case VA = "Holy See";
    case HN = "Honduras";
    case HK = "Hong Kong";
    case HU = "Hungary";
    case IS = "Iceland";
    case IN = "India";
    case ID = "Indonesia";
    case IR = "Iran";
    case IQ = "Iraq";
    case IE = "Ireland";
    case IM = "Isle of Man";
    case IL = "Israel";
    case IT = "Italy";
    case CI = "Ivory Coast";
    case JM = "Jamaica";
    case JP = "Japan";
    case JE = "Jersey";
    case JO = "Jordan";
    case KZ = "Kazakhstan";
    case KE = "Kenya";
    case KI = "Kiribati";
    case KR = "Republic of Korea";
    case KW = "Kuwait";
    case KG = "Kyrgyzstan";
    case LA = "Laos";
    case LV = "Latvia";
    case LB = "Lebanon";
    case LS = "Lesotho";
    case LR = "Liberia";
    case LY = "Libya";
    case LI = "Liechtenstein";
    case LT = "Lithuania";
    case LU = "Luxembourg";
    case MO = "Macao";
    case MK = "Macedonia";
    case MG = "Madagascar";
    case MW = "Malawi";
    case MY = "Malaysia";
    case MV = "Maldives";
    case ML = "Mali";
    case MT = "Malta";
    case MH = "Marshall Islands (USA)";
    case MQ = "Martinique";
    case MR = "Mauritania";
    case MU = "Mauritius";
    case YT = "Mayotte";
    case MX = "Mexico";
    case FM = "Micronesia (USA)";
    case MD = "Moldova";
    case MC = "Monaco";
    case MN = "Mongolia";
    case ME = "Montenegro";
    case MS = "Montserrat";
    case MA = "Morocco";
    case MZ = "Mozambique";
    case MM = "Myanmar";
    case NA = "Namibia";
    case NR = "Nauru";
    case NP = "Nepal";
    case AN = "Netherlands Antilles";
    case NL = "Netherlands";
    case NC = "New Caledonia";
    case NZ = "New Zealand";
    case NI = "Nicaragua";
    case NE = "Niger";
    case NG = "Nigeria";
    case NU = "Niue";
    case NF = "Norfolk Island";
    case KP = "North Korea";
    case MP = "Northern Mariana Islands (USA)";
    case NO = "Norway";
    case OM = "Oman";
    case PK = "Pakistan";
    case PW = "Palau (USA)";
    case PS = "Palestinian Territory";
    case PA = "Panama";
    case PG = "Papua New Guinea";
    case PY = "Paraguay";
    case PE = "Peru";
    case PH = "Philippines";
    case PN = "Pitcairn Island";
    case PL = "Poland";
    case PT = "Portugal";
    case PR = "Puerto Rico (USA)";
    case QA = "Qatar";
    case RE = "Reunion";
    case RO = "Romania";
    case RU = "Russia";
    case RW = "Rwanda";
    case BL = "Saint Barthelemy";
    case SH = "Saint Helena";
    case KN = "Saint Kitts and Nevis";
    case LC = "Saint Lucia";
    case MF = "Saint Martin";
    case PM = "Saint Pierre and Miquelon";
    case VC = "Saint Vincent and the Grenadines";
    case WS = "Samoa";
    case SM = "San Marino";
    case ST = "Sao Tome and Principe";
    case SA = "Saudi Arabia";
    case SN = "Senegal";
    case RS = "Serbia";
    case SC = "Seychelles";
    case SL = "Sierra Leone";
    case SG = "Singapore";
    case SX = "Sint Maarten (Dutch)";
    case SK = "Slovakia";
    case SI = "Slovenia";
    case SB = "Solomon Islands";
    case SO = "Somalia";
    case ZA = "South Africa";
    case GS = "South Georgia and the South Sandwich Islands";
    case SS = "South Sudan";
    case ES = "Spain";
    case LK = "Sri Lanka";
    case SD = "Sudan";
    case SR = "Suriname";
    case SJ = "Svalbard and Jan Mayen Islands";
    case SZ = "Swaziland";
    case SE = "Sweden";
    case CH = "Switzerland";
    case SY = "Syria";
    case TW = "Taiwan";
    case TJ = "Tajikistan";
    case TZ = "Tanzania";
    case TH = "Thailand";
    case TL = "Timor-Leste";
    case TG = "Togo";
    case TK = "Tokelau";
    case TO = "Tonga";
    case TT = "Trinidad and Tobago";
    case TN = "Tunisia";
    case TR = "Turkey";
    case TM = "Turkmenistan";
    case TC = "Turks and Caicos Islands";
    case TV = "Tuvalu";
    case UG = "Uganda";
    case UA = "Ukraine";
    case AE = "United Arab Emirates";
    case GB = "United Kingdom";
    case UM = "United States Minor Outlying Islands";
    case VI = "US Virgin Islands";
    case US = "United States";
    case UY = "Uruguay";
    case UZ = "Uzbekistan";
    case VU = "Vanuatu";
    case VE = "Venezuela";
    case VN = "Viet Nam";
    case WF = "Wallis and Futuna Islands";
    case EH = "Western Sahara";
    case YE = "Yemen";
    case ZM = "Zambia";
    case ZW = "Zimbabwe";
    case UNKNOWN = "";

    public static function reverse(string $name): CountriesISO2
    {
        return match ($name) {
            "AF" => CountriesISO2::AF,
            "AX" => CountriesISO2::AX,
            "AL" => CountriesISO2::AL,
            "DZ" => CountriesISO2::DZ,
            "AS" => CountriesISO2::AS,
            "AD" => CountriesISO2::AD,
            "AO" => CountriesISO2::AO,
            "AI" => CountriesISO2::AI,
            "AQ" => CountriesISO2::AQ,
            "AG" => CountriesISO2::AG,
            "AR" => CountriesISO2::AR,
            "AM" => CountriesISO2::AM,
            "AW" => CountriesISO2::AW,
            "AU" => CountriesISO2::AU,
            "AT" => CountriesISO2::AT,
            "AZ" => CountriesISO2::AZ,
            "BS" => CountriesISO2::BS,
            "BH" => CountriesISO2::BH,
            "BD" => CountriesISO2::BD,
            "BB" => CountriesISO2::BB,
            "BY" => CountriesISO2::BY,
            "BE" => CountriesISO2::BE,
            "BZ" => CountriesISO2::BZ,
            "BJ" => CountriesISO2::BJ,
            "BM" => CountriesISO2::BM,
            "BT" => CountriesISO2::BT,
            "BO" => CountriesISO2::BO,
            "BQ" => CountriesISO2::BQ,
            "BA" => CountriesISO2::BA,
            "BW" => CountriesISO2::BW,
            "BR" => CountriesISO2::BR,
            "IO" => CountriesISO2::IO,
            "VG" => CountriesISO2::VG,
            "BN" => CountriesISO2::BN,
            "BG" => CountriesISO2::BG,
            "BF" => CountriesISO2::BF,
            "BI" => CountriesISO2::BI,
            "KH" => CountriesISO2::KH,
            "CM" => CountriesISO2::CM,
            "CA" => CountriesISO2::CA,
            "CV" => CountriesISO2::CV,
            "KY" => CountriesISO2::KY,
            "CF" => CountriesISO2::CF,
            "TD" => CountriesISO2::TD,
            "CL" => CountriesISO2::CL,
            "CN" => CountriesISO2::CN,
            "CX" => CountriesISO2::CX,
            "CC" => CountriesISO2::CC,
            "CO" => CountriesISO2::CO,
            "KM" => CountriesISO2::KM,
            "CD" => CountriesISO2::CD,
            "CG" => CountriesISO2::CG,
            "CK" => CountriesISO2::CK,
            "CR" => CountriesISO2::CR,
            "HR" => CountriesISO2::HR,
            "CU" => CountriesISO2::CU,
            "CW" => CountriesISO2::CW,
            "CY" => CountriesISO2::CY,
            "CZ" => CountriesISO2::CZ,
            "DK" => CountriesISO2::DK,
            "DJ" => CountriesISO2::DJ,
            "DM" => CountriesISO2::DM,
            "DO" => CountriesISO2::DO,
            "EC" => CountriesISO2::EC,
            "EG" => CountriesISO2::EG,
            "SV" => CountriesISO2::SV,
            "GQ" => CountriesISO2::GQ,
            "ER" => CountriesISO2::ER,
            "EE" => CountriesISO2::EE,
            "ET" => CountriesISO2::ET,
            "FK" => CountriesISO2::FK,
            "FO" => CountriesISO2::FO,
            "FJ" => CountriesISO2::FJ,
            "FI" => CountriesISO2::FI,
            "FR" => CountriesISO2::FR,
            "GF" => CountriesISO2::GF,
            "PF" => CountriesISO2::PF,
            "TF" => CountriesISO2::TF,
            "GA" => CountriesISO2::GA,
            "GM" => CountriesISO2::GM,
            "GE" => CountriesISO2::GE,
            "DE" => CountriesISO2::DE,
            "GH" => CountriesISO2::GH,
            "GI" => CountriesISO2::GI,
            "GR" => CountriesISO2::GR,
            "GL" => CountriesISO2::GL,
            "GD" => CountriesISO2::GD,
            "GP" => CountriesISO2::GP,
            "GU" => CountriesISO2::GU,
            "GT" => CountriesISO2::GT,
            "GG" => CountriesISO2::GG,
            "GN" => CountriesISO2::GN,
            "GW" => CountriesISO2::GW,
            "GY" => CountriesISO2::GY,
            "HT" => CountriesISO2::HT,
            "VA" => CountriesISO2::VA,
            "HN" => CountriesISO2::HN,
            "HK" => CountriesISO2::HK,
            "HU" => CountriesISO2::HU,
            "IS" => CountriesISO2::IS,
            "IN" => CountriesISO2::IN,
            "ID" => CountriesISO2::ID,
            "IR" => CountriesISO2::IR,
            "IQ" => CountriesISO2::IQ,
            "IE" => CountriesISO2::IE,
            "IM" => CountriesISO2::IM,
            "IL" => CountriesISO2::IL,
            "IT" => CountriesISO2::IT,
            "CI" => CountriesISO2::CI,
            "JM" => CountriesISO2::JM,
            "JP" => CountriesISO2::JP,
            "JE" => CountriesISO2::JE,
            "JO" => CountriesISO2::JO,
            "KZ" => CountriesISO2::KZ,
            "KE" => CountriesISO2::KE,
            "KI" => CountriesISO2::KI,
            "KR" => CountriesISO2::KR,
            "KW" => CountriesISO2::KW,
            "KG" => CountriesISO2::KG,
            "LA" => CountriesISO2::LA,
            "LV" => CountriesISO2::LV,
            "LB" => CountriesISO2::LB,
            "LS" => CountriesISO2::LS,
            "LR" => CountriesISO2::LR,
            "LY" => CountriesISO2::LY,
            "LI" => CountriesISO2::LI,
            "LT" => CountriesISO2::LT,
            "LU" => CountriesISO2::LU,
            "MO" => CountriesISO2::MO,
            "MK" => CountriesISO2::MK,
            "MG" => CountriesISO2::MG,
            "MW" => CountriesISO2::MW,
            "MY" => CountriesISO2::MY,
            "MV" => CountriesISO2::MV,
            "ML" => CountriesISO2::ML,
            "MT" => CountriesISO2::MT,
            "MH" => CountriesISO2::MH,
            "MQ" => CountriesISO2::MQ,
            "MR" => CountriesISO2::MR,
            "MU" => CountriesISO2::MU,
            "YT" => CountriesISO2::YT,
            "MX" => CountriesISO2::MX,
            "FM" => CountriesISO2::FM,
            "MD" => CountriesISO2::MD,
            "MC" => CountriesISO2::MC,
            "MN" => CountriesISO2::MN,
            "ME" => CountriesISO2::ME,
            "MS" => CountriesISO2::MS,
            "MA" => CountriesISO2::MA,
            "MZ" => CountriesISO2::MZ,
            "MM" => CountriesISO2::MM,
            "NA" => CountriesISO2::NA,
            "NR" => CountriesISO2::NR,
            "NP" => CountriesISO2::NP,
            "AN" => CountriesISO2::AN,
            "NL" => CountriesISO2::NL,
            "NC" => CountriesISO2::NC,
            "NZ" => CountriesISO2::NZ,
            "NI" => CountriesISO2::NI,
            "NE" => CountriesISO2::NE,
            "NG" => CountriesISO2::NG,
            "NU" => CountriesISO2::NU,
            "NF" => CountriesISO2::NF,
            "KP" => CountriesISO2::KP,
            "MP" => CountriesISO2::MP,
            "NO" => CountriesISO2::NO,
            "OM" => CountriesISO2::OM,
            "PK" => CountriesISO2::PK,
            "PW" => CountriesISO2::PW,
            "PS" => CountriesISO2::PS,
            "PA" => CountriesISO2::PA,
            "PG" => CountriesISO2::PG,
            "PY" => CountriesISO2::PY,
            "PE" => CountriesISO2::PE,
            "PH" => CountriesISO2::PH,
            "PN" => CountriesISO2::PN,
            "PL" => CountriesISO2::PL,
            "PT" => CountriesISO2::PT,
            "PR" => CountriesISO2::PR,
            "QA" => CountriesISO2::QA,
            "RE" => CountriesISO2::RE,
            "RO" => CountriesISO2::RO,
            "RU" => CountriesISO2::RU,
            "RW" => CountriesISO2::RW,
            "BL" => CountriesISO2::BL,
            "SH" => CountriesISO2::SH,
            "KN" => CountriesISO2::KN,
            "LC" => CountriesISO2::LC,
            "MF" => CountriesISO2::MF,
            "PM" => CountriesISO2::PM,
            "VC" => CountriesISO2::VC,
            "WS" => CountriesISO2::WS,
            "SM" => CountriesISO2::SM,
            "ST" => CountriesISO2::ST,
            "SA" => CountriesISO2::SA,
            "SN" => CountriesISO2::SN,
            "RS" => CountriesISO2::RS,
            "SC" => CountriesISO2::SC,
            "SL" => CountriesISO2::SL,
            "SG" => CountriesISO2::SG,
            "SX" => CountriesISO2::SX,
            "SK" => CountriesISO2::SK,
            "SI" => CountriesISO2::SI,
            "SB" => CountriesISO2::SB,
            "SO" => CountriesISO2::SO,
            "ZA" => CountriesISO2::ZA,
            "GS" => CountriesISO2::GS,
            "SS" => CountriesISO2::SS,
            "ES" => CountriesISO2::ES,
            "LK" => CountriesISO2::LK,
            "SD" => CountriesISO2::SD,
            "SR" => CountriesISO2::SR,
            "SJ" => CountriesISO2::SJ,
            "SZ" => CountriesISO2::SZ,
            "SE" => CountriesISO2::SE,
            "CH" => CountriesISO2::CH,
            "SY" => CountriesISO2::SY,
            "TW" => CountriesISO2::TW,
            "TJ" => CountriesISO2::TJ,
            "TZ" => CountriesISO2::TZ,
            "TH" => CountriesISO2::TH,
            "TL" => CountriesISO2::TL,
            "TG" => CountriesISO2::TG,
            "TK" => CountriesISO2::TK,
            "TO" => CountriesISO2::TO,
            "TT" => CountriesISO2::TT,
            "TN" => CountriesISO2::TN,
            "TR" => CountriesISO2::TR,
            "TM" => CountriesISO2::TM,
            "TC" => CountriesISO2::TC,
            "TV" => CountriesISO2::TV,
            "UG" => CountriesISO2::UG,
            "UA" => CountriesISO2::UA,
            "AE" => CountriesISO2::AE,
            "GB" => CountriesISO2::GB,
            "UM" => CountriesISO2::UM,
            "VI" => CountriesISO2::VI,
            "US" => CountriesISO2::US,
            "UY" => CountriesISO2::UY,
            "UZ" => CountriesISO2::UZ,
            "VU" => CountriesISO2::VU,
            "VE" => CountriesISO2::VE,
            "VN" => CountriesISO2::VN,
            "WF" => CountriesISO2::WF,
            "EH" => CountriesISO2::EH,
            "YE" => CountriesISO2::YE,
            "ZM" => CountriesISO2::ZM,
            "ZW" => CountriesISO2::ZW,
            default => CountriesISO2::UNKNOWN
        };
    }
}
