<?php
/*
 * Copyright (c) 2022 - Do Group LLC - All Right Reserved.
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Emanuele (ebalo) Balsamo <emanuele.balsamo@do-inc.co>, 2022
 */

namespace Doinc\Modules\SmartyStreetApi\Models\DTOs;

use Doinc\Modules\SmartyStreetApi\Enums\SmartyAddressPrecision;
use Doinc\Modules\SmartyStreetApi\Enums\SmartyChangesScale;
use Doinc\Modules\SmartyStreetApi\Enums\SmartyVerificationStatus;
use Illuminate\Support\Arr;
use JessArcher\CastableDataTransferObject\CastableDataTransferObject;

class SmartyRootDTO extends CastableDataTransferObject
{
    /**
     * A unique identifier generated by you for this address for use within your application.
     * The output will be identical to the value you provided in the request input_id.
     * @var string|null
     */
    public ?string $input_id;

    /**
     * The name of the recipient, firm, or company at this address.
     * The output will be identical to the input.
     * @var string|null
     */
    public ?string $organization;

    /**
     * If address_precision = DeliveryPoint or Premise, these fields will contain the correctly formatted address for
     * mailing in the relevant country, split into individual address lines.
     * (Note: These fields may contain values that are not referenced in the address components.)
     *
     * If address_precision ≠ DeliveryPoint or Premise, the address fields may contain standardized address information
     * or even the original input data.
     * @var string|null
     */
    public ?string $address1;
    public ?string $address2;
    public ?string $address3;
    public ?string $address4;
    public ?string $address5;
    public ?string $address6;
    public ?string $address7;
    public ?string $address8;
    public ?string $address9;
    public ?string $address10;
    public ?string $address11;
    public ?string $address12;

    /**
     * Contains the various basic elements of the address.
     * @var SmartyComponentsDTO
     */
    public SmartyComponentsDTO $components;

    /**
     * Contains ancillary data about each address.
     * @var SmartyMetadataDTO
     */
    public SmartyMetadataDTO $metadata;

    /**
     * Contains information about the validation and the precision of the output address.
     * @var SmartyAnalysisDTO
     */
    public SmartyAnalysisDTO $analysis;

    /**
     * Check if the resulting value is valid
     * @return bool
     */
    public function isValid(): bool
    {
        $verification_status = $this->analysis->verification_status;
        $address_precision = $this->analysis->address_precision;
        return (
                $verification_status === SmartyVerificationStatus::AMBIGUOUS ||
                $verification_status === SmartyVerificationStatus::VERIFIED
            ) && (
                $address_precision === SmartyAddressPrecision::PREMISE ||
                $address_precision === SmartyAddressPrecision::DELIVERY_POINT
            );
    }

    /**
     * Check if one or more values has changes
     * @return bool
     */
    public function hasChanges(): bool
    {
        return in_array(
            true,
            collect(Arr::dot($this->analysis->changes->all()))->map(function ($item) {
                return in_array(
                    $item,
                    [
                        SmartyChangesScale::VERIFIED_ALIAS_CHANGE,
                        SmartyChangesScale::VERIFIED_SMALL_CHANGE,
                        SmartyChangesScale::VERIFIED_LARGE_CHANGE,
                        SmartyChangesScale::ADDED,
                        SmartyChangesScale::IDENTIFIED_ALIAS_CHANGE,
                        SmartyChangesScale::IDENTIFIED_CONTEXT_CHANGE,
                    ],
                    true
                );
            })->toArray(),
            true
        );
    }
}
