<?php

namespace App\Http\Wrappers\Enums;

enum SodiumKeyLength: int
{
    case KEYPAIR_SEED_BYTES = 32; // SODIUM_CRYPTO_KX_SEEDBYTES;
    case DERIVATION_CONTEXT_BYTES = 8; // SODIUM_CRYPTO_KDF_CONTEXTBYTES;
    case KDF_BYTES = 32; // SODIUM_CRYPTO_KDF_KEYBYTES;
    case PWHASH_SALT_BYTES = 16; // SODIUM_CRYPTO_PWHASH_SALTBYTES;
    case ASYMMETRIC_ENCRYPTION_NONCE = 24; // SODIUM_CRYPTO_BOX_NONCEBYTES;
    case SYMMETRIC_ENCRYPTION_NONCE = 24; // SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES;
    case SYMMETRIC_ENCRYPTION_KEY = 32;
}
